                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      SET standard_conforming_strings = ON;
DROP TABLE IF EXISTS "public"."points" CASCADE;
BEGIN;
CREATE TABLE "public"."points"();
ALTER TABLE "public"."points" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "points_pk" PRIMARY KEY;
SELECT AddGeometryColumn('public','points','geom',4326,'POINT',2);
ALTER TABLE "public"."points" ADD COLUMN "osm_id" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "name" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "barrier" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "highway" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "ref" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "address" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "is_in" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "place" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "man_made" VARCHAR;
ALTER TABLE "public"."points" ADD COLUMN "other_tags" VARCHAR;
COMMIT;
DROP TABLE IF EXISTS "public"."lines" CASCADE;
BEGIN;
CREATE TABLE "public"."lines"();
ALTER TABLE "public"."lines" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "lines_pk" PRIMARY KEY;
SELECT AddGeometryColumn('public','lines','geom',4326,'LINESTRING',2);
ALTER TABLE "public"."lines" ADD COLUMN "osm_id" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "name" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "highway" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "waterway" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "aerialway" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "barrier" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "man_made" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "railway" VARCHAR;
ALTER TABLE "public"."lines" ADD COLUMN "z_order" INTEGER;
ALTER TABLE "public"."lines" ADD COLUMN "other_tags" VARCHAR;
COMMIT;
DROP TABLE IF EXISTS "public"."multilinestrings" CASCADE;
BEGIN;
CREATE TABLE "public"."multilinestrings"();
ALTER TABLE "public"."multilinestrings" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "multilinestrings_pk" PRIMARY KEY;
SELECT AddGeometryColumn('public','multilinestrings','geom',4326,'MULTILINESTRING',2);
ALTER TABLE "public"."multilinestrings" ADD COLUMN "osm_id" VARCHAR;
ALTER TABLE "public"."multilinestrings" ADD COLUMN "name" VARCHAR;
ALTER TABLE "public"."multilinestrings" ADD COLUMN "type" VARCHAR;
ALTER TABLE "public"."multilinestrings" ADD COLUMN "other_tags" VARCHAR;
COMMIT;
DROP TABLE IF EXISTS "public"."multipolygons" CASCADE;
BEGIN;
CREATE TABLE "public"."multipolygons"();
ALTER TABLE "public"."multipolygons" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "multipolygons_pk" PRIMARY KEY;
SELECT AddGeometryColumn('public','multipolygons','geom',4326,'MULTIPOLYGON',2);
ALTER TABLE "public"."multipolygons" ADD COLUMN "osm_id" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "osm_way_id" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "name" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "type" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "aeroway" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "amenity" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "admin_level" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "barrier" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "boundary" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "building" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "craft" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "geological" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "historic" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "land_area" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "landuse" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "leisure" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "man_made" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "military" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "natural" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "office" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "place" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "shop" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "sport" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "tourism" VARCHAR;
ALTER TABLE "public"."multipolygons" ADD COLUMN "other_tags" VARCHAR;
COMMIT;
DROP TABLE IF EXISTS "public"."other_relations" CASCADE;
BEGIN;
CREATE TABLE "public"."other_relations"();
ALTER TABLE "public"."other_relations" ADD COLUMN "ogc_fid" SERIAL CONSTRAINT "other_relations_pk" PRIMARY KEY;
SELECT AddGeometryColumn('public','other_relations','geom',4326,'GEOMETRYCOLLECTION',2);
ALTER TABLE "public"."other_relations" ADD COLUMN "osm_id" VARCHAR;
ALTER TABLE "public"."other_relations" ADD COLUMN "name" VARCHAR;
ALTER TABLE "public"."other_relations" ADD COLUMN "type" VARCHAR;
ALTER TABLE "public"."other_relations" ADD COLUMN "other_tags" VARCHAR;
INSERT INTO "public"."points" ("geom", "osm_id", "name", "other_tags") VALUES ('0101000020E6100000C8670D3991445240E1F4899702CB4040', '34992852', 'ایئرپورٹ روڈ', '"name:ar"=>"طريق المطار","name:en"=>"Airport Road","name:ur"=>"ایئرپورٹ روڈ"');
INSERT INTO "public"."points" ("geom", "osm_id", "highway") VALUES ('0101000020E61000000460F2F5EB4052409D329298FBD84040', '35182799', 'traffic_signals');
INSERT INTO "public"."points" ("geom", "osm_id", "highway") VALUES ('0101000020E610000000C5C892394152402EE983C025D84040', '53094812', 'traffic_signals');
INSERT INTO "public"."points" ("geom", "osm_id", "name", "place", "other_tags") VALUES ('0101000020E61000005260014C199452405F69CF1BDDF54140', '58568637', 'گلگت', 'city', '"alt_name:ar"=>"كلكيت;غلغيت;غيلغيت;غلغت","capital"=>"4","is_capital"=>"state","name:ar"=>"كلكت","name:az"=>"Gilgit","name:be"=>"Гілгіт","name:bn"=>"গিলগিট","name:bsk"=>"Geelt","name:cs"=>"Gilgit","name:de"=>"Gilgit","name:el"=>"Γκιλγκίτ","name:en"=>"Gilgit","name:es"=>"Gilgit","name:et"=>"Gilgit","name:fa"=>"گلگت","name:fr"=>"Gilgit","name:he"=>"גילגיט","name:hi"=>"गिलगित","name:hr"=>"Gilgit","name:ja"=>"ギルギット","name:kn"=>"ಗಿಲ್ಗಿಟ್","name:ko"=>"길기트","name:ks"=>"گلگت","name:ml"=>"ഗിൽഗിത്ത്","name:pl"=>"Gilgit","name:ru"=>"Гилгит","name:scl"=>"گلیٗت","name:sl"=>"Gilgit","name:sr"=>"Гилгит","name:te"=>"గిల్గిట్","name:uk"=>"Гілгіт","name:ur"=>"گلگت","name:vi"=>"Gilgit","name:zh"=>"吉尔吉特","wikidata"=>"Q609024","wikipedia"=>"ur:گلگت"');
INSERT INTO "public"."points" ("geom", "osm_id", "other_tags") VALUES ('0101000020E61000001893FE5E0A2E5240FEA902FFA50A4140', '58679642', '"pipeline"=>"valve"');
INSERT INTO "public"."points" ("geom", "osm_id", "name", "place", "other_tags") VALUES ('0101000020E6100000F086342A704352400D90C3BBB7CB4040', '58744442', 'راولپنڈی', 'city', '"admin_level"=>"5","capital"=>"5","name:ar"=>"راولبندي","name:az-Arab"=>"راولپندی","name:azb"=>"راولپندی","name:be"=>"Равалпіндзі","name:cs"=>"Rávalpindí","name:de"=>"Rawalpindi","name:el"=>"Ραβαλπίντι","name:en"=>"Rawalpindi","name:es"=>"Rawalpindi","name:et"=>"Rāwalpindi","name:eu"=>"Rawalpindi","name:fa"=>"راولپندی","name:fr"=>"Rawalpindi","name:he"=>"רוואלפינדי","name:hi"=>"रावलपिंडी","name:hr"=>"Ravalpindi","name:ja"=>"ラーワルピンディー","name:kn"=>"ರಾವಲ್ಪಿಂಡಿ","name:ks"=>"راولپنڈی","name:ml"=>"രാവൽപിണ്ഡി","name:ne"=>"रावलपिंडी","name:pa"=>"ਰਾਵਲਪਿੰਡੀ","name:pl"=>"Rawalpindi","name:pnb"=>"راولپنڈی","name:ps"=>"راولپنډي","name:pt"=>"Rawalpindi","name:ru"=>"Равалпинди","name:sd"=>"راولپنڊي","name:skr"=>"راولپنڈی","name:sl"=>"Ravalpindi","name:sr"=>"Равалпинди","name:te"=>"రావల్పిండి","name:ug"=>"راۋالپىندى","name:uk"=>"Равалпінді","name:ur"=>"راولپنڈی","name:zh"=>"拉瓦尔品第","population"=>"2098231","wikidata"=>"Q93230","wikipedia"=>"ur:راولپنڈی"');
CREATE INDEX "points_geom_geom_idx" ON "public"."points" USING GIST ("geom");
CREATE INDEX "lines_geom_geom_idx" ON "public"."lines" USING GIST ("geom");
CREATE INDEX "multilinestrings_geom_geom_idx" ON "public"."multilinestrings" USING GIST ("geom");
CREATE INDEX "multipolygons_geom_geom_idx" ON "public"."multipolygons" USING GIST ("geom");
CREATE INDEX "other_relations_geom_geom_idx" ON "public"."other_relations" USING GIST ("geom");
COMMIT;
